config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :communities do
    resources :posts, only: %i[show new edit create update destroy] do
      resources :likes, only: %i[create destroy]
      resources :comments
    end
    resources :applies, only: %i[index create destroy]
    resources :belongings, only: %i[index create destroy]
  end

  resources :users, only: %i[index show] do
    member do
      get :follower, :followed
    end
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :score, presence: true
  validates :content, presence: true, length: { maximum: 300 }
  validates :visitday, presence: true

  belongs_to :user
  belongs_to :post, counter_cache: :comments_count
  has_one_attached :image
  include ImageValidators
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :validate_comment, only: %i[edit update destroy]
  before_action :new_comment_limited, only: [:new]

  def create
    @post = Post.find(params[:post_id])
    @community = Community.find(params[:community_id])
    @code = Code.all

    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to community_post_url(@comment.post.community, @comment.post), notice: "「#{@comment.post.title}」の口コミを登録しました。"
    else
      render :new
    end
  end

  def update
    comment = Comment.find(params[:id])
    comment.update!(comment_params)
    redirect_to community_post_url(comment.post.community, comment.post), notice: "「#{comment.post.title}」の口コミを更新しました。"
  end

  def destroy
    return unless @comment.destroy

    redirect_to community_post_url(@comment.post.community, @comment.post), notice: "「#{@comment.post.title}」の口コミを削除しました。"
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @code = Code.all
  end

  def edit
    @post = Post.find(params[:post_id])
    @community = Community.find(params[:community_id])
    @code = Code.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:image, :score, :visitday, :content, :scene, :people, :post_id)
  end

  def validate_comment
    @comment = Comment.find(params[:id])
    redirect_to community_post_path(@comment.post.community, @comment.post) if @comment.user_id != current_user.id
  end

  def new_comment_limited
    @community = Community.find(params[:community_id])
    return if @community.user_belonging?(current_user)

    redirect_to community_post_path(@community, @community.post), alert: "所属ユーザのみ口コミができます"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% if comment.errors.present? %>
    <%= render partial:'shared/error_explanation', locals:{object: comment} %>
<% end %>
<%= form_with(model: [community, post, comment], local: true) do |f| %>
    <div class="form-group">
        <%= f.label "写真のアップロード" %>
        <%= f.file_field :image, class:'form-control-file' %>
    </div>
    <div class="form-group">
        <span class="must">必須</span><%= f.label "評価" %><br>
        <%= f.collection_select :score, code.where(code_id: "5"), :code, :name, {include_blank: '評価を選択'}, {class: "form-control"} %>
    </div>
    <div class="form-group">
        <span class="must">必須</span><%= f.label "口コミ内容" %>
        <%= f.text_area :content, row:5, class: 'form-control', id:'comment-content' %>
    </div>
    <div class="form-group">
        <span class="must">必須</span><%= f.label "訪問日" %><br>
        <%= f.date_field :visitday, class:'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label "利用シーン" %><br>
        <%= f.collection_select :scene, code.where(code_id: "3"), :code, :name, {include_blank: '利用シーンを選択'}, {class: "form-control"} %>
    </div>
    <div class="form-group">
        <%= f.label "利用人数" %><br>
        <%= f.collection_select :people, code.where(code_id: "4"), :code, :name, {include_blank: '利用人数を選択'}, {class: "form-control"} %>
    </div>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.submit "口コミを登録する", class:'btn btn-primary' %>
    &nbsp;<%= link_to "戻る", :back %>
<% end %>

app/views/comments/edit.html.erb
<% provide(:title, "口コミ編集") %>
<% breadcrumb :comment_edit, @community, @post, @comment %>
<%= breadcrumbs separator: " &rsaquo; " %>
<br>
<div class="container">
    <div class="comment-edit">
        <h3><i class="fas fa-comments"></i> 口コミを編集する</h3><br>
        <div class="comment-form">
            <%= render partial:'form', locals:{post: @post, community: @community, code: @code, comment: @comment} %>
        </div>
    </div>
</div>

app/views/comments/new.html.erb
<% provide(:title, "口コミ投稿") %>
<% breadcrumb :comment_new, @community, @post %>
<%= breadcrumbs separator: " &rsaquo; " %>
<br>
<div class="container">
    <div class="comment-new">
        <h3><i class="fas fa-comments"></i> 口コミを登録する</h3><br>
        <div class="comment-form">
            <%= render partial:'form', locals: {post: @post, community: @community, code: @code, comment: @comment} %>
        </div>
    </div>
</div>

app/views/comments/show.html.erb
<% provide(:title, "口コミ詳細") %>
<% breadcrumb :comment_show, @comment.post.community, @comment.post, @comment %>
<%= breadcrumbs separator: " &rsaquo; " %>
<br>
<div class="container comment-wrapper">
    <h3><i class="fas fa-comment"></i> 口コミの詳細  （<%= @comment.post.title %>）</h3>
    <div class="comment-linkbtn">
        <% if @comment.user == current_user %>
            <%= link_to "編集",edit_community_post_comment_path(@comment.post.community,@comment.post,@comment), class:"mini-green-link-btn font-bold text-line-none cmt-edit" %>
        <% end %>
        <% if @comment.user == current_user %>
            <%= link_to "削除", community_post_comment_path(@comment.post.community,@comment.post,@comment), method: :delete, data:{ confirm: "口コミを削除します。よろしいですか？" } ,class:"mini-red-link-btn font-bold text-line-none cmt-delete" %>
        <% end %>
    </div>
    <div class="row cmnt-main">
        <div class="col-sm-12 col-md-6">
        <% if @comment.image.attached? %>
            <%= image_tag @comment.image, class:"card-img-top" %>
        <% else %>
            <%= image_tag ("no_image.png"), class:"card-img-top" %>
        <% end %>
        </div>
        <div class="col-sm-12 col-md-6 cmt-info-wrapper">
            <div class="row cmt-info1">
                <div class="col-6 cmt">
                    <span class="rating-title">評価</span>&emsp;<%= @comment.score %>
                    <div class="cmnt-info mt-1">
                        <div class="scene-tag"><span class="mini-item-name-gray">利用シーン：</span><%= user_code_name("3",@comment.scene) %></div>
                        <div class="people-tag"><span class="mini-item-name-gray">利用人数：</span><%= user_code_name("4",@comment.people) %></div>
                        <div><span class="mini-item-name-gray">訪問日：</span><%= @comment.visitday.strftime("%Y/%m/%d") %></div>
                    </div>
                </div>
                <div class="col-6 m-auto0">
                    <%= link_to user_path(@comment.user), class:"text-line-none" do %>
                        <% if @comment.user.image.attached? %>
                            <%= image_tag @comment.user.image, class:"user-icon" %>
                        <% else %>
                            <%= image_tag ("no_image.png"), class:"user-icon" %>
                        <% end %>
                            <span class="font-size-mid"><%= @comment.user.username %></span>
                    <% end %>
                </div>
            </div>
            <div class="content-box">
                <%= simple_format(h(@comment.content), {}, sanitize: false, wrapper_tag:"div") %>
            </div>
        </div>
    </div>
</div>