config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :communities do
    resources :posts, only: %i[show new edit create update destroy] do
      resources :likes, only: %i[create destroy]
      resources :comments
    end
    resources :applies, only: %i[index create destroy]
    resources :belongings, only: %i[index create destroy]
  end

  resources :users, only: %i[index show] do
    member do
      get :follower, :followed
    end
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :user
  belongs_to :community
  validates :user_id, presence: true
  validates :community_id, presence: true
  validates  :user_id, uniqueness: { scope: :community_id }
  validates  :community_id, uniqueness: { scope: :user_id }
end

app/models/belonging.rb
class Belonging < ApplicationRecord
  belongs_to :user
  belongs_to :community
  validates :user_id, presence: true
  validates :community_id, presence: true

  validates  :user_id, uniqueness: { scope: :community_id }
  validates  :community_id, uniqueness: { scope: :user_id }
end

app/models/code.rb
class Code < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :score, presence: true
  validates :content, presence: true, length: { maximum: 300 }
  validates :visitday, presence: true

  belongs_to :user
  belongs_to :post, counter_cache: :comments_count
  has_one_attached :image
  include ImageValidators
end

app/models/community.rb
class Community < ApplicationRecord
  validates :name, uniqueness: { scope: :create_user_id }, presence: true, length: { maximum: 20 }
  validates :description, length: { maximum: 50 }
  validates :create_user_id, presence: true
  validates :publish_flg, presence: true
  include ImageValidators

  belongs_to :create_user, class_name: "User"
  has_many :posts, dependent: :destroy
  has_many :belongings, dependent: :destroy
  has_many :applies, dependent: :destroy
  has_one_attached :image

  has_many :users, through: :belongings # コミュニティに所属しているユーザ

  # ユーザがコミュニティに所属していればtrueを返す
  def user_belonging?(user)
    users.include?(user)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
  validates :user_id, presence: true
  validates :post_id, presence: true

  validates :user_id, uniqueness: { scope: :post_id }
  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :description, presence: true, length: { maximum: 200 }
  validates :prefecture_code, presence: true
  validates :rest_type, presence: true
  validate :validate_image
  has_one_attached :image
  include ImageValidators

  belongs_to :user
  belongs_to :community
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  include JpPrefecture
  jp_prefecture :prefecture_code
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  validates  :follower_id, uniqueness: { scope: :followed_id }
  validates  :followed_id, uniqueness: { scope: :follower_id }
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, authentication_keys: [:email]
  validates :email, presence: true, uniqueness: true
  validates :username, length: { maximum: 30 }
  has_one_attached :image
  include ImageValidators

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :belongings, dependent: :destroy
  has_many :applies, dependent: :destroy

  has_many :communities, through: :belongings # ユーザが所属しているコミュニティ

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = "ゲストユーザー"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "グルコミュ"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end

  # リンクの動的制御
  def order_link_active(name, path, order)
    class_name =  if params[:comment_order].nil? && order == 'updated_at'
                    'mini-orange-link-btn'
                  elsif order == params[:comment_order]
                    'mini-orange-link-btn'
                  else
                    'mini-green-link-btn'
                  end
    link_to name, path + '?comment_order=' + order, class: class_name
  end

  # 年代計算
  def age_calc(birth_ym)
    age = (Time.zone.today.strftime("%Y%m%d").to_i - birth_ym.strftime("%Y%m%d").to_i) / 10_000
    age < 10 ? "10代未満" : "#{age / 10}0代"
  end

  # コードのIDからコード名称を表示する
  def user_code_name(id, code)
    Code.find_by(code_id: id, code: code)&.name
  end

  # ユーザのグループにおける権限を取得
  def user_admin_flg(user, community)
    flg = Belonging.find_by(user_id: user.id, community_id: community.id) if user
    flg&.admin_flg
  end

  # 各グループの所属人数を算出
  def community_member_calc(community)
    Belonging.where(community_id: community.id).count
  end

  # 各グループ内の口コミ総件数を算出
  def community_comment_calc(community)
    community.posts.inject(0) { |sum, com| sum + com.comments.count }
  end

  # グループの作成者ユーザオブジェクト取得
  def get_create_user(community)
    User.find(community.create_user_id)
  end

  # グループ内の店における一番多いタイプを取得
  def post_type_most(community, type)
    num = []
    community.posts.each do |p|
      num << p.prefecture_code if (type == '1') && p.prefecture_code.present? # エリア
      num << p.rest_type if (type == '2') && p.rest_type.present? # 店タイプ
    end
    return if num.empty?

    most = num.max_by { |v| num.count(v) }
    case type
    when '1'
      JpPrefecture::Prefecture.find(code: most).try(:name) # 都道府県コードから名称を取得
    when '2'
      user_code_name(type, most) # 店タイプコードから名称を取得
    end
  end

  # 店舗ジャンルのclassを返す
  def rest_type_class(id)
    case id
    when "1"
      "rest-type-1"
    when "2"
      "rest-type-2"
    when "3"
      "rest-type-3"
    else
      "rest-type-null"
    end
  end
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/helpers/belongings_helper.rb
module BelongingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
  </head>

  <body>
    <div class="wrapper">
      <%= render "shared/header" %>
      <%= yield %>
      <div class="push"></div>
      <%= render "shared/footer" %>

      <script type="text/javascript">
        <% flash.each do |name, msg| %>
          <% name = "success" if name == "notice" %>
          <% name = "error" if name == "alert" %>
          toastr['<%= name %>']('<%= msg %>');
        <% end %>
      </script>
    </div>
  </body>
</html>

app/views/shared/_comments.html.erb
<div id="comments_area">
    <% comments.each do |c| %>
        <%= link_to community_post_comment_path(c.post.community,c.post,c), class: "cmnt-link" do %>
            <div class="cmnt">
                <div class="row">
                    <div class="col-sm-12 col-md-5 cmntuser">
                    <% if c.image.attached? %>
                        <%= image_tag c.image, class:"cmt-img" %>
                    <% else %>
                        <%= image_tag ("no_image.png"), class:"cmt-img" %>
                    <% end %>
                    <span class="font-size-mini"><%= c.post.title if request.fullpath.include?('users/') %></span> 
                    </div>
                    <div class="col-sm-12 col-md-4 cmntttl">
                        <span class="rating-title">評価</span>&nbsp;<%= c.score %><br>
                        <span class="mini-item-name-gray">訪問日：</span><span class="font-size-mid"><%= c.visitday.strftime("%Y/%m/%d") %></span><br>
                        <span class="font-size-mid"><%= c.content.truncate(30) %></span>
                    </div>
                    <div class="col-sm-12 col-md-3">
                        <% if c.user.image.attached? %>
                            <%= image_tag c.user.image, class:"user-icon" %>
                        <% else %>
                            <%= image_tag ("no_image.png"), class:"user-icon" %>
                        <% end %>
                        <div class="font-size-mid"><%= c.user.username %></div>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/shared/_communities.html.erb
<!-- カード START -->
<div class="card">
    <%= link_to community_path(community) do %>
        <% if community.image.attached? %>
            <%= image_tag community.image, class:"community-img" %>
        <% else %>
            <%= image_tag ("no_image.png"), class:"community-img" %>
        <% end %>
    <% end %>
    <div class="card-body">
        <p class="card-title">
            <%= link_to community.name, community_path(community) %>
            <% if community.publish_flg == 1 %>
                <i class="fas fa-lock"></i>
            <% end %>
        </p>
        <div class="card-text">
            <i class="fas fa-users"></i>&nbsp<%= community.users.size %>人
            &nbsp&nbsp<i class="fas fa-utensils"></i>&nbsp<%= community.posts.size %>店舗
            &nbsp&nbsp<i class="fas fa-comments"></i>&nbsp<%= community_comment_calc(community) %>件<br>
            <span class="font-size-mini">
                投稿が多い都道府県：<%= post_type_most(community, '1') %><br> <!-- 都道府県 -->
                投稿が多い店ジャンル：<%= post_type_most(community, '2') %><br><!-- 店タイプ -->
            </span>
            <% if current_user and current_user.applies.find_by(community_id: community).present? %>
                <span class="green-btn font-bold mt-2">加入申請中</span>
            <% end %>
        </div>
    </div>
</div>
<!-- カード END -->

app/views/shared/_error_explanation.html.erb
<div id="error_explanation">
    <div class="alert alert-error">
        フォームの入力内容に <%= object.errors.count %>個のエラーがあります。
    </div>
    <ul>
    <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
</div>

app/views/shared/_follow.html.erb
<div id="follow-<%= user.id %>" class="follow">
    <div class="follow-count">
        <div class="follow-container">
            <span class="follow-label">フォロー</span><br>
            <%= link_to user.follower.count, follower_user_path(user), class: "follow-count-link" %>
        </div>
        <div class="follower-container">
            <span class="follow-label">フォロワー</span><br>
            <%= link_to user.followed.count, followed_user_path(user), class: "follow-count-link" %>
        </div>
    </div>
    <div class="follow-link">
        <% if user_signed_in? %>
            <% if current_user.id != user.id %>
                <% if current_user.following?(user) %>
                    <%= link_to 'フォロー中', unfollow_path(user.id), method: :post, remote: true, class: "unfollow-btn" %>
                <% else %>
                    <%= link_to 'フォロー', follow_path(user.id), method: :post, remote: true, class: "follow-btn" %>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer>
    <div class="main">
        <div class="logo">グルコミュ</div>
        <div class="text">Copyright © Gourcommu Inc. All rights reserved</div>
    </div>
</footer>

app/views/shared/_gmap-new.html.erb
<div class="form-group" id="gmapnew" style="padding-top: 50px;">
  <input type="text" id="address" class="serchaddress" placeholder="店名を入れて住所検索" autocomplete="off">
  &nbsp<button class="copybtn" onclick="copy()">住所をコピー</button>
  <div id="map" style="max-width: 500px; height: 400px;"></div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAPS_API_KEY'] %>&libraries=places&callback=initAutocomplete" async defer></script>

app/views/shared/_header.html.erb
<header class="app-title navbar navbar-expand-md navbar-dark bg-dark">
    <%= link_to "グルコミュ", root_path, class:"header_logo navbar-brand text-line-none" %>
    <nav>
        <div class="loginstauts">
        <% if user_signed_in? %>
            <span class="loginuser-name"><strong><%= current_user.username %></strong>でログインしています。</span>
            <%= link_to "マイページ", user_path(current_user) %>
            | <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data:{ confirm: "ログアウトします。よろしいですか？" } %>
        <% else %>
            <%= link_to "ユーザ登録", new_user_registration_path %> |
            <%= link_to "ログイン", new_user_session_path %>
        <% end %>
            | <%= link_to "グループ一覧", communities_path %>
            | <%= link_to "ユーザ一覧", users_path %>
        </div>
    </nav>
</header>

app/views/shared/_like.html.erb
<div class="like_btn-<%= post.id %>">
<% if user_signed_in? %>
    <% like = Like.find_by(user_id: current_user.id ,post_id: post.id) %>
    <% if like != nil %>
        <%= link_to community_post_like_path(community,post, like), method: :delete, remote: true do %>
            <i class="fas fa-heart"></i>
        <% end %>
    <% else %>
        <%= link_to community_post_likes_path(community,post), method: :post, remote: true do %>
            <i class="far fa-heart"></i>
        <% end %>
    <% end %>
    <span>
        <%= post.likes_count %>
    </span>
<% else %>
    <i class="fas fa-heart"></i>
    <span>
        <%= post.likes_count %>
    </span>
<% end %>
</div>

app/views/shared/_posts.html.erb
<div class="row post-index">
    <% posts.each do |post| %>
        <div class = "col-12 col-sm-6 col-lg-4 mb-5">
            <!-- カード START -->
            <div class="card card-post">
                <%= link_to community_post_path(post.community,post) do %>
                    <% if post.image.attached? %>
                        <%= image_tag post.image, class:"card-img-top" %>
                    <% else %>
                        <%= image_tag ("no_image.png"), class:"card-img-top" %>
                    <% end %>
                <% end %>
                <div class="card-body">
                    <p class="card-title"><%= post.title %></p>
                    <div class="card-text">
                        <div><%= post.prefecture.name if post.prefecture_code.present? %></div>
                        <div><span class="mini-item-name-gray">更新日：</span><%= post.updated_at.strftime("%Y/%m/%d") %></div>
                        <div><i class="fas fa-comments"></i> <%= post.comments.count %></div>
                        <span class="<%= rest_type_class(post.rest_type) %> font-size-mid text-color-white mt-2 p-1"><%= user_code_name("2", post.rest_type) %></span>
                    </div>
                    <div class="text-right" id="likes_buttons_<%= post.id %>">
                        <%= render partial: 'shared/like', locals: {community: post.community, post: post} %>
                    </div>
                </div>
            </div>
            <!-- カード END -->
        </div>
    <% end %>
</div>