config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :communities do
    resources :posts, only: %i[show new edit create update destroy] do
      resources :likes, only: %i[create destroy]
      resources :comments
    end
    resources :applies, only: %i[index create destroy]
    resources :belongings, only: %i[index create destroy]
  end

  resources :users, only: %i[index show] do
    member do
      get :follower, :followed
    end
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :description, presence: true, length: { maximum: 200 }
  validates :prefecture_code, presence: true
  validates :rest_type, presence: true
  validate :validate_image
  has_one_attached :image
  include ImageValidators

  belongs_to :user
  belongs_to :community
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  include JpPrefecture
  jp_prefecture :prefecture_code
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :validate_post, only: %i[edit update destroy]
  before_action :new_post_limited, only: [:new]
  before_action :set_community

  def show
    @post = Post.find(params[:id])
    @pref_name = set_pref_name
    @comments = @post.comments
    @comments = set_comment_order(@comments, params[:comment_order])
    @score = @comments.average(:score)&.round(1) # 口コミの評価平均
  end

  def new
    @post = Post.new
    @code = Code.all
  end

  def edit
    @post = @community.posts.find(params[:id])
    @code = Code.all
  end

  def create
    @post = @community.posts.build(post_params)
    @code = Code.all

    if @post.save
      redirect_to community_url(@community), notice: "お店「#{@post.title}」を登録しました。"
    else
      render :new
    end
  end

  def update
    post = @community.posts.find(params[:id])
    post.update!(post_params)
    redirect_to community_url(@community), notice: "お店「#{post.title}」を更新しました。"
  end

  def destroy
    post = @community.posts.find(params[:id])
    post.destroy!
    redirect_to community_url(@community), notice: "お店「#{post.title}」を削除しました。"
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :image, :area, :prefecture_code, :rest_type, :address).merge(user_id: current_user.id)
  end

  def set_comment_order(comments, cmnt_order)
    order_key = 'updated_at'
    case cmnt_order
    when 'updated_at'
      order_key = 'updated_at'
    when 'score'
      order_key = 'score'
    when 'visitday'
      order_key = 'visitday'
    end
    comments.order(order_key)
  end

  def validate_post
    @post = Post.find(params[:id])
    return unless @post.user_id != current_user.id

    redirect_to community_post_path(@post.community, @post), alert: "作成ユーザのみ変更操作ができます"
  end

  def new_post_limited
    @community = Community.find(params[:community_id])
    redirect_to community_path(@community), alert: "所属ユーザのみ新規作成ができます" unless @community.user_belonging?(current_user)
  end

  def set_community
    @community = Community.find(params[:community_id])
  end

  def set_pref_name
    @post.prefecture_code.present? ? @post.prefecture.name : ""
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if post.errors.present? %>
    <%= render partial:'shared/error_explanation', locals:{object: post} %>
<% end %>
<%= form_with(model: [community,post] ,local: true) do |f| %>
    <div class="form-group">
        <%= f.label "写真のアップロード" %>
        <%= f.file_field :image %>
    </div>
    <div class="form-group">
        <span class="must">必須</span><%= f.label "店名" %>
        <%= f.text_field :title, class:'form-control', id: 'title_name' %>
    </div>
    <div class="form-group">
        <span class="must">必須</span><%= f.label "お店の説明" %>
        <%= f.text_area :description, row:5, class: 'form-control', id:'post_description' %>
    </div>
    <div class="form-group">
        <span class="must">必須</span><%= f.label "都道府県" %><br>
        <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, {include_blank: '都道府県を選択してください'}, {class: "form-control"} %>
    </div>
    <div class="form-group">
        <label for="post_住所">住所（<a href="#gmapnew">住所検索</a>から貼り付け可能）</label>
        <%= f.text_field :address, class: 'form-control', id:'post_address', placeholder: "住所" %>
    </div>
    <div class="form-group">
        <span class="must">必須</span><%= f.label "料理ジャンル" %><br>
        <%= f.collection_select :rest_type, code.where(code_id: "2"), :code, :name, {include_blank: '料理ジャンルを選択してください'}, {class: "form-control"} %>
    </div>
    <%= f.submit "更新する", class:'btn btn-primary' %>
    <%= link_to '戻る', community_posts_path(community), class:'btn' %>
<% end %>
<%= render partial: 'shared/gmap-new' %>

app/views/posts/edit.html.erb
<% provide(:title, "店舗編集") %>
<% breadcrumb :post_edit, @community, @post %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="container">
    <div class="post-edit">
        <h3><i class="fas fa-utensils"></i> お店情報を編集する</h3><br>
        <div class="post-form">
            <%= render partial:'form', locals:{post: @post, code: @code, community: @community} %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "店舗投稿") %>
<% breadcrumb :post_new, @community %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="container">
    <div class="post-new">
        <h3><i class="fas fa-utensils"></i> お店を登録する</h3><br>
        <div class="post-form">
            <%= render partial:'form', locals:{post: @post, code: @code, community: @community} %>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "店舗詳細") %>
<% breadcrumb :post_show, @post.community, @post %>
<%= breadcrumbs separator: " &rsaquo; " %>
<br>
<div class="container shopwrapper">
    <h3 class="shoptitle"><i class="fas fa-utensils"></i> <%= @post.title %></h3>
    <div class="shop-linkbtn">
        <div class="shop-edit">
        <% if @post.user == current_user %>
            <%= link_to "編集",edit_community_post_path(@post.community,@post), class:"mini-green-link-btn font-bold text-line-none" %>
        <% end %>
        </div>
        <div class="shop-delete">
        <% if @post.user == current_user %>
            <%= link_to "削除", community_post_path(@post.community,@post), method: :delete, data:{ confirm: "投稿「#{@post.title}」を削除します。よろしいですか？" } ,class:"mini-red-link-btn font-bold text-line-none" %>
        <% end %>
        </div>
    </div>
    <div class="shopinfo">
        <div class="row">
            <div class="col-sm-12 col-md-6">
            <% if @post.image.attached? %>
                <%= image_tag @post.image, class:"card-img-top" %>
            <% else %>
                <%= image_tag ("no_image.png"), class:"card-img-top" %>
            <% end %>
            </div>
            <div class="col-sm-12 col-md-6">
                <span class="rating-title">評価</span>&nbsp;
                <% if @score %>
                    <%= @score %>/5
                <% else %>
                    口コミなし
                <% end %>
                <div class="shopinfo-header">
                    <div class="post-<%= @post.id %> shopinfo-like">
                        <%= render partial: 'shared/like', locals: {community: @post.community, post: @post} %>
                    </div>&nbsp&nbsp
                    <div id="comments_area">
                        <i class="fas fa-comments"></i> <%= @comments.count %>
                    </div>&nbsp&nbsp
                    <span class="<%= rest_type_class(@post.rest_type) %> font-size-mid text-color-white mt-2 p-1"><%= user_code_name("2", @post.rest_type) %></span>
                </div>
                <span class="mini-item-name-gray">更新日：<%= @post.updated_at.strftime("%Y/%m/%d") %></span><br>
                <span class="shopadr"><i class="fas fa-map-marker-alt"></i> <%= @post.address %></span><br>
                <%= simple_format(h(@post.description), { class: 'post-description' }, wrapper_tag:"div") %>
            </div>
        </div>
    </div>
    <div class="col-sm-12 commentlist">
        <h3 class="cmntlst-title"><i class="fas fa-comments"></i><br>口コミ一覧</h3>
        <div class="order-link">
            <%= order_link_active('投稿日順', community_post_path(@post.community), 'updated_at') %>
            <%= order_link_active('評価順', community_post_path(@post.community), 'score') %>
            <%= order_link_active('訪問日順', community_post_path(@post.community), 'visitday') %>
        </div>
        <!-- 口コミ一覧 START -->
        <%= render partial:'shared/comments', locals:{post: @post, comments: @comments } %>
        <!-- 口コミ一覧 END -->
    </div>
</div>
<%= link_to '口コミ登録', new_community_post_comment_path(@post.community,@post), class: 'new-btn' %>