config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :communities do
    resources :posts, only: %i[show new edit create update destroy] do
      resources :likes, only: %i[create destroy]
      resources :comments
    end
    resources :applies, only: %i[index create destroy]
    resources :belongings, only: %i[index create destroy]
  end

  resources :users, only: %i[index show] do
    member do
      get :follower, :followed
    end
  end

  post 'follow/:id' => 'relationships#create', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow' # フォロー外す
end

app/models/community.rb
class Community < ApplicationRecord
  validates :name, uniqueness: { scope: :create_user_id }, presence: true, length: { maximum: 20 }
  validates :description, length: { maximum: 50 }
  validates :create_user_id, presence: true
  validates :publish_flg, presence: true
  include ImageValidators

  belongs_to :create_user, class_name: "User"
  has_many :posts, dependent: :destroy
  has_many :belongings, dependent: :destroy
  has_many :applies, dependent: :destroy
  has_one_attached :image

  has_many :users, through: :belongings # コミュニティに所属しているユーザ

  # ユーザがコミュニティに所属していればtrueを返す
  def user_belonging?(user)
    users.include?(user)
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :validate_community, only: %i[edit update destroy]

  def index
    # 検索オブジェクト
    @search = Community.ransack(params[:q])
    # 検索結果
    @communities = @search.result
    @communities = @communities.page(params[:page]).per(12)
  end

  def show
    @community = Community.find(params[:id])
    @belongings = Belonging.where(community_id: @community.id)
    @code = Code.all
    # 検索オブジェクト
    @search = Post.ransack(params[:q])
    # 検索結果
    @posts = @search.result
    @posts = @posts.where(community_id: @community.id)
    @posts = @posts.page(params[:page]).per(9)
    return unless current_user

    @belonging = Belonging.find_by(community_id: @community.id, user_id: current_user.id)
    @apply = Apply.find_by(community_id: @community.id, user_id: current_user.id)
  end

  def new
    @community = Community.new
    @code = Code.all
  end

  def edit
    @community = Community.find(params[:id])
    @code = Code.all
  end

  def create
    @community = current_user.communities.build(community_params)

    if @community.save
      Belonging.create!(community_id: @community.id, user_id: current_user.id, admin_flg: '1')
      redirect_to communities_url, notice: "グループ「#{@community.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    community = current_user.communities.find(params[:id])
    community.update!(community_params)
    redirect_to community_url(community), notice: "グループ「#{community.name}」を更新しました。"
  end

  def destroy
    community = Community.find(params[:id])
    community.destroy
    redirect_to communities_url, notice: "グループ「#{community.name}」を削除しました。"
  end

  private

  def community_params
    params.require(:community).permit(:name, :create_user_id, :publish_flg, :description, :image)
  end

  def validate_community
    @community = Community.find(params[:id])
    redirect_to community_path(@community), alert: "作成ユーザのみ変更操作ができます" if @community.create_user_id != current_user.id
  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<% if community.errors.present? %>
    <%= render partial:'shared/error_explanation', locals:{object: community} %>
<% end %>
<%= form_with(model: community, local:true) do |f| %>
    <div class="form-group">
        <%= f.label "写真のアップロード" %><br>
        <%= f.file_field :image %>
    </div>
    <div class="form-group">
        <span class="must">必須</span><%= f.label "グループの名前（20字以内）" %>
        <%= f.text_field :name, class:'form-control', id: 'community_name' %>
    </div>
    <div class="form-group">
        <%= f.label "グループの説明（50字以内）" %>
        <%= f.text_area :description, row:5, class: 'form-control', id:'community_description' %>
    </div>
    <div class="form-group">
        <label class="control-label">公開/非公開の選択</label>
        <div class="form-check">
            <%= f.radio_button :publish_flg, 0, class: "form-check-input" %>
            <%= f.label :publish_flg, "公開", class: "form-check-label" %>
        </div>
        <div class="form-check">
            <%= f.radio_button :publish_flg, 1, class: "form-check-input" %>
            <%= f.label :publish_flg, "非公開", class: "form-check-label" %>
        </div>
    </div>
    <%= f.hidden_field :create_user_id, value: current_user.id %>
    <%= f.submit "更新する", class:'btn btn-primary' %>
    <%= link_to '戻る', communities_path, class:'btn' %>
<% end %>

app/views/communities/edit.html.erb
<% provide(:title, "グループ編集") %>
<% breadcrumb :community_edit, @community %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="container">
    <div class="community-edit">
        <h3><i class="fas fa-users"></i> グループ情報を編集する</h3><br>
        <div class="community-form">
            <%= render partial:'form', locals:{community: @community, code: @code} %>
        </div>
    </div>
</div>

app/views/communities/index.html.erb
<% provide(:title, "グループ一覧") %>
<div class="container mt-3">
    <div class="row">
        <div class="communityindex col-12">
            <!-- グループ一覧 START -->
            <div class="container communities">
                <!-- タイトル START -->
                <h3 class="commulst-title"><i class="fas fa-users"></i>&nbspグループ一覧</h3>
                <!-- タイトル END -->
                <!-- 検索 START -->
                <div class="searchform container">
                    <%= search_form_for @search do |f| %>
                        <div class="row">
                            <div class="form-group cond1 col-sm-7 m-0">
                                <%= f.search_field :name_cont, class:"form-control" ,placeholder: "グループ名で探す "  %>
                            </div>
                            <div class="form-group cond3 col-sm-3 m-0">
                                <%= f.select( :sorts, {'並び替え': 'id asc', '作成日の新しい順': 'created_at desc', '作成日の古い順': 'created_at asc' }, {},{class: "form-control"}) %>
                            </div>
                            <div class="form-group cond_sbtn col-sm-2">
                                <%= f.submit "検索", class: 'sbtn' %>
                            </div>
                        </div>
                    <% end %>
                </div>
                <!-- 検索 END -->
                <div class="center">
                    <%= paginate @communities %>
                </div>
                <div class="row">
                    <% @communities.each do |com| %>
                        <div class = "col-sm-6 col-md-4 col-lg-3 mb-5">
                            <%= render partial:'shared/communities', locals:{community: com} %>
                        </div>
                    <% end %>
                </div>
                <div class="center">
                    <%= paginate @communities %>
                </div>
            </div>
            <!-- グループ一覧 END -->
            <div class="d-none d-md-block">
                <%= link_to new_community_path, class: 'new-btn' do %>
                    新規作成
                <% end %>
            </div>            
        </div>
    </div>
</div>

app/views/communities/new.html.erb
<% provide(:title, "グループ作成") %>
<% breadcrumb :community_new %>
<%= breadcrumbs separator: " &rsaquo; " %>
<div class="container">
    <div class="community-new">
        <h3><i class="fas fa-users"></i> 新規グループを作成する</h3><br>
        <div class="community-form">
            <%= render partial:'form', locals:{community: @community, code: @code} %>
        </div>
    </div>
</div>

app/views/communities/show.html.erb
<% provide(:title, "グループ詳細") %>
<% breadcrumb :community_show, @community %>
<%= breadcrumbs separator: " &rsaquo; " %>
<br>
<div class="container community-show">
    <div class="row">
        <div class="communitydtl col-lg-3 col-xs-12 mb-2">
            <% if @community.image.attached? %>
                <%= image_tag @community.image, class:"community-img" %>
            <% else %>
                <%= image_tag ("no_image.png"), class:"community-img" %>
            <% end %>
            <div class="community-linkbtn">
                <div class="community-edit-btn">
                <% if @community.create_user == current_user %>
                    <%= link_to "編集",edit_community_path(@community), class:"mini-green-link-btn font-bold text-line-none" %>
                <% end %>
                </div>
                <div class="community-delete-btn">
                <% if @community.create_user == current_user %>
                    <%= link_to "削除", community_path(@community), method: :delete, data:{ confirm: "グループ「#{@community.name}」を削除します。よろしいですか？" } ,class:"mini-red-link-btn font-bold text-line-none" %>
                <% end %>
                </div>
            </div>
            <!-- ログインユーザが当該グループに所属している場合 -->
            <% if @community.user_belonging?(current_user) and @community.id != 1 %>
                <%= link_to '退会する', community_belonging_path(@community, @belonging), method: :delete, data:{ confirm: "グループ「#{@community.name}」を退会します。よろしいですか？" } ,class:"mini-red-link-btn font-bold text-line-none" %>
            <!-- 当該グループには所属していないが、ログインはしている場合 -->
            <% elsif current_user and @community.id != 1 %>
                <% if @apply %>
                    <%= link_to '申請取消', community_apply_path(@community, @apply), method: :delete, data:{ confirm: "加入申請を取り消します。よろしいですか？" }, class: "mini-red-link-btn font-bold text-line-none" %>
                <% else %>
                    <%= link_to '加入申請', community_applies_path(@community), method: :post, data:{ confirm: "加入申請を行います。よろしいですか？" }, class: "mini-green-link-btn font-bold text-line-none" %>
                <% end %>
            <% end %>
            <div class="my-3">
                <p class="comm-name">
                    <%= @community.name %>
                    <% if @community.publish_flg == 1 %>
                        <i class="fas fa-lock"></i>
                    <% end %>
                </p>
            <!-- 所属しているor公開グループのみ表示 START -->
            <% if @community.user_belonging?(current_user) or @community.publish_flg == 0 %>
                <%= simple_format(h(@community.description), { class: 'comm-desc' }) %>
                <% if user_admin_flg(current_user,@community) == 1 %>
                    <%= link_to "承認待ち一覧", community_applies_path(@community), class:"btn btn-primary" %>
                <% end %>
            <% end %>
            <!-- 所属しているor公開グループのみ表示 END -->
            </div>
        <!-- 所属しているor公開グループのみ表示 START -->
        <% if @community.user_belonging?(current_user) or @community.publish_flg == 0 %>
            <!-- 所属メンバー一覧 START -->
            <p class="user-index">所属ユーザ一覧</p>
            <div class="container">
                <div class="row">
                    <% @belongings.each do |belonging| %>
                        <div class="col-2 col-xs-2 col-md-2 col-lg-4">
                            <% if belonging.admin_flg == 1 %>
                                <div class="admin"><i class="fas fa-shield-alt"></i>管理者</div>
                            <% else %>
                                <div class="admin">&nbsp</div>
                            <% end %>
                            <%= link_to user_path(belonging.user) do %>
                                <% if belonging.user.image.attached? %>
                                    <%= image_tag belonging.user.image, class:"user-icon" %>
                                <% else %>
                                    <%= image_tag ("no_image.png"), class:"user-icon" %>
                                <% end %>
                            <% end %>
                            <div class="belong-username"><%= belonging.user.username %></div>
                        </div>
                    <% end %>
                </div>
            </div>
            <!-- 所属メンバー一覧 END -->
        <% end %>
        <!-- 所属しているor公開グループのみ表示 END -->
        </div>
        <div class="communityindex col-lg-9 col-sm-12">
        <!-- 所属しているor公開グループのみ表示 START -->
        <% if @community.user_belonging?(current_user) or @community.publish_flg == 0 %>
            <!-- 検索フォーム -->
            <div class="searchform container">
                <%= search_form_for @search, url: community_path(@community) do |f| %>
                    <div class="row">
                        <div class="form-group cond1 col-sm-4">
                            <%= f.search_field :title_or_user_username_cont, class:"form-control" ,placeholder: "店名またはユーザー名"  %>
                        </div>
                        <div class="form-group cond2 col-sm-3">
                            <%= f.collection_select( :prefecture_code_eq_any, JpPrefecture::Prefecture.all, :code, :name, {include_blank: '都道府県'}, {class: "form-control"}) %>
                        </div>
                        <div class="form-group cond2 col-sm-3">
                            <%= f.collection_select( :rest_type_eq_any, @code.where(code_id: "2"), :code, :name, {include_blank: '料理ジャンル'}, {class: "form-control"}) %>
                        </div>
                        <div class="form-group cond3 col-sm-3">
                            <%= f.select( :sorts, {'並び替え': 'updated_at desc', 'いいねの多い順': 'likes_count desc', 'コメントの多い順': 'comments_count desc', '更新日の新しい順': 'updated_at desc', '更新日の古い順': 'updated_at asc' }, {},{class: "form-control"}) %>
                        </div>
                        <%= f.hidden_field :community_id, value: @community.id %>
                        <div class="form-group cond_sbtn col-sm-2 mt-2">
                            <%= f.submit "検索", class: 'sbtn' %>
                        </div>
                    </div>
                <% end %>
            </div>
            <!-- 店一覧 START -->
            <div class="container">
                <div class="center">
                    <%= paginate @posts %>
                </div>
                    <%= render partial:'shared/posts', locals:{posts: @posts} %>
                <div class="center">
                    <%= paginate @posts %>
                </div>
            </div>
            <!-- 店一覧 END -->
        <% end %>
        <!-- 所属しているor公開グループのみ表示 END -->
        </div>
    </div>
</div>
<div class="d-none d-md-block">
    <%= link_to '新規投稿', new_community_post_path(@community), class: 'new-btn' %>
</div>